# Generated by Django 5.0.4 on 2024-04-19 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Faculty name')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lecture Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Lecture Surname')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Subject Name')),
                ('description', models.TextField(verbose_name='Subject Description')),
                ('syllabus', models.FileField(upload_to='syllabi/', verbose_name='Syllabus')),
                ('faculties', models.ManyToManyField(related_name='subjects', to='student.faculty')),
                ('lecturers', models.ManyToManyField(related_name='subjects', to='student.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Student Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Student Surname')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.faculty')),
                ('subjects', models.ManyToManyField(limit_choices_to={'faculties__id': models.F('faculty_id')}, related_name='students', to='student.subject')),
            ],
        ),
    ]
