# Generated by Django 5.0.4 on 2024-04-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_options_student_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lecturer Name')),
                ('surname', models.CharField(max_length=255, verbose_name='Lecturer Surname')),
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
            },
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='student.subject', verbose_name='Subjects'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='syllabus',
            field=models.FileField(upload_to='syllabuses/', verbose_name='Syllabus'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lecturers',
            field=models.ManyToManyField(related_name='subjects', to='student.lecturer'),
        ),
    ]
